CREATE TABLE guests (
                        id BIGINT AUTO_INCREMENT PRIMARY KEY,
                        guest_id VARCHAR(50) UNIQUE NOT NULL,
                        first_name VARCHAR(100) NOT NULL,
                        last_name VARCHAR(100) NOT NULL,
                        email VARCHAR(255) UNIQUE NOT NULL,
                        phone VARCHAR(50) NOT NULL,
                        date_of_birth DATE,
                        nationality VARCHAR(100),
                        passport_number VARCHAR(50),
                        address VARCHAR(500),
                        city VARCHAR(100),
                        state VARCHAR(100),
                        country VARCHAR(100),
                        zip_code VARCHAR(20),
                        guest_type VARCHAR(20) NOT NULL,
                        preferences VARCHAR(1000),
                        special_requests VARCHAR(1000),
                        is_active BOOLEAN NOT NULL DEFAULT TRUE,
                        loyalty_points INT NOT NULL DEFAULT 0,
                        loyalty_tier VARCHAR(20) NOT NULL DEFAULT 'BRONZE',
                        created_at DATETIME NOT NULL,
                        updated_at DATETIME NOT NULL,
                        created_by VARCHAR(255),
                        notes VARCHAR(1000),

                        INDEX idx_guest_id (guest_id),
                        INDEX idx_email (email),
                        INDEX idx_guest_type (guest_type),
                        INDEX idx_loyalty_tier (loyalty_tier),
                        INDEX idx_is_active (is_active),
                        INDEX idx_created_at (created_at)
);