CREATE TABLE room_bookings (
                               id BIGINT AUTO_INCREMENT PRIMARY KEY,
                               booking_number VARCHAR(50) UNIQUE NOT NULL,
                               room_id VARCHAR(50) NOT NULL,
                               guest_id VARCHAR(50),
                               guest_name VARCHAR(255) NOT NULL,
                               guest_email VARCHAR(255) NOT NULL,
                               guest_phone VARCHAR(50) NOT NULL,
                               check_in_date DATE NOT NULL,
                               check_out_date DATE NOT NULL,
                               number_of_guests INT NOT NULL,
                               number_of_nights INT NOT NULL,
                               room_price DECIMAL(10, 2) NOT NULL,
                               total_amount DECIMAL(10, 2) NOT NULL,
                               status VARCHAR(50) NOT NULL,
                               special_requests TEXT,
                               booking_date_time DATETIME NOT NULL,
                               last_modified_date_time DATETIME NOT NULL,
                               booked_by VARCHAR(255),
                               INDEX idx_booking_number (booking_number),
                               INDEX idx_guest_email (guest_email),
                               INDEX idx_room_id (room_id),
                               INDEX idx_status (status),
                               INDEX idx_check_in_date (check_in_date)
);

CREATE TABLE table_bookings (
                                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                booking_number VARCHAR(50) UNIQUE NOT NULL,
                                table_id VARCHAR(50) NOT NULL,
                                guest_id VARCHAR(50),
                                guest_name VARCHAR(255) NOT NULL,
                                guest_email VARCHAR(255) NOT NULL,
                                guest_phone VARCHAR(50) NOT NULL,
                                reservation_date DATE NOT NULL,
                                reservation_time TIME NOT NULL,
                                number_of_guests INT NOT NULL,
                                duration_minutes INT NOT NULL,
                                reservation_fee DECIMAL(10, 2) NOT NULL,
                                status VARCHAR(50) NOT NULL,
                                special_requests TEXT,
                                booking_date_time DATETIME NOT NULL,
                                last_modified_date_time DATETIME NOT NULL,
                                booked_by VARCHAR(255),
                                INDEX idx_booking_number (booking_number),
                                INDEX idx_guest_email (guest_email),
                                INDEX idx_table_id (table_id),
                                INDEX idx_status (status),
                                INDEX idx_reservation_date (reservation_date)
);