CREATE TABLE staff_members (
                               id BIGINT AUTO_INCREMENT PRIMARY KEY,
                               staff_id VARCHAR(50) UNIQUE NOT NULL,
                               first_name VARCHAR(100) NOT NULL,
                               last_name VARCHAR(100) NOT NULL,
                               email VARCHAR(255) UNIQUE NOT NULL,
                               phone VARCHAR(50) NOT NULL,
                               date_of_birth DATE,
                               address VARCHAR(500),
                               city VARCHAR(100),
                               state VARCHAR(100),
                               country VARCHAR(100),
                               zip_code VARCHAR(20),
                               role VARCHAR(50) NOT NULL,
                               department VARCHAR(50) NOT NULL,
                               join_date DATE NOT NULL,
                               resignation_date DATE,
                               employment_status VARCHAR(20) NOT NULL,
                               salary DECIMAL(10, 2) NOT NULL,
                               bank_account_number VARCHAR(50),
                               emergency_contact_name VARCHAR(255),
                               emergency_contact_phone VARCHAR(50),
                               qualifications VARCHAR(1000),
                               notes VARCHAR(1000),
                               created_at DATETIME NOT NULL,
                               updated_at DATETIME NOT NULL,
                               created_by VARCHAR(255),

                               INDEX idx_staff_id (staff_id),
                               INDEX idx_email (email),
                               INDEX idx_role (role),
                               INDEX idx_department (department),
                               INDEX idx_employment_status (employment_status),
                               INDEX idx_join_date (join_date)
);