CREATE TABLE payments (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          payment_id VARCHAR(50) UNIQUE NOT NULL,
                          booking_number VARCHAR(50) NOT NULL,
                          payment_type VARCHAR(20) NOT NULL,
                          amount DECIMAL(10, 2) NOT NULL,
                          currency VARCHAR(10) NOT NULL,
                          payment_method VARCHAR(20) NOT NULL,
                          payment_status VARCHAR(20) NOT NULL,
                          transaction_id VARCHAR(100),
                          guest_email VARCHAR(255) NOT NULL,
                          guest_name VARCHAR(255) NOT NULL,
                          description VARCHAR(1000),
                          payment_date_time DATETIME NOT NULL,
                          created_at DATETIME NOT NULL,
                          updated_at DATETIME NOT NULL,
                          processed_by VARCHAR(255),
                          failure_reason VARCHAR(500),
                          card_last4_digits VARCHAR(4),
                          card_type VARCHAR(20),

                          INDEX idx_payment_id (payment_id),
                          INDEX idx_booking_number (booking_number),
                          INDEX idx_guest_email (guest_email),
                          INDEX idx_payment_status (payment_status),
                          INDEX idx_payment_type (payment_type),
                          INDEX idx_transaction_id (transaction_id),
                          INDEX idx_payment_date_time (payment_date_time)
);