---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  LOKI_URL: "http://loki.default.svc.cluster.local:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.default.svc.cluster.local:9411"
  BOOKING_SERVICE_URL: "http://booking-service.default.svc.cluster.local:8080"
  ORDER_SERVICE_URL: "http://order-service.default.svc.cluster.local:8081"
  GUEST_SERVICE_URL: "http://guest-service.default.svc.cluster.local:8082"
  HOTEL_SERVICE_URL: "http://hotel-service.default.svc.cluster.local:8084"
  STAFF_SERVICE_URL: "http://staff-service.default.svc.cluster.local:8087"
  RESTUARANT_SERVICE_URL: "http://restuarant-service.default.svc.cluster.local:8086"
  NOTIFICATION_SERVICE_URL: "http://notification-service.default.svc.cluster.local:8083"
  PAYMENT_SERVICE_URL: "http://payment-service.default.svc.cluster.local:8085"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "broker.default.svc.cluster.local:29092"